export const notes = [
  "C1",
  "C#1",
  "D1",
  "D#1",
  "E1",
  "F1",
  "F#1",
  "G1",
  "G#1",
  "A2",
  "A#2",
  "B2",
  "C2",
  "C#2",
  "D2",
  "D#2",
  "E2",
  "F2",
  "F#2",
  "G2",
  "G#2",
  "A3",
  "A#3",
  "B3",
  "C3",
  "C#3",
  "D3",
  "D#3",
  "E3",
  "F3",
  "F#3",
  "G3",
  "G#3",
  "A4",
  "A#4",
  "B4",
];

export const audios = {
  C1: new Audio("/tones/c1.mp3"),
  "C#1": new Audio("/tones/cs1.mp3"),
  D1: new Audio("/tones/d1.mp3"),
  "D#1": new Audio("/tones/ds1.mp3"),
  E1: new Audio("/tones/e1.mp3"),
  F1: new Audio("/tones/f1.mp3"),
  "F#1": new Audio("/tones/fs1.mp3"),
  G1: new Audio("/tones/g1.mp3"),
  "G#1": new Audio("/tones/gs1.mp3"),
  A2: new Audio("/tones/a2.mp3"),
  "A#2": new Audio("/tones/as2.mp3"),
  B2: new Audio("/tones/b2.mp3"),
  C2: new Audio("/tones/c2.mp3"),
  "C#2": new Audio("/tones/cs2.mp3"),
  D2: new Audio("/tones/d2.mp3"),
  "D#2": new Audio("/tones/ds2.mp3"),
  E2: new Audio("/tones/e2.mp3"),
  F2: new Audio("/tones/f2.mp3"),
  "F#2": new Audio("/tones/fs2.mp3"),
  G2: new Audio("/tones/g2.mp3"),
  "G#2": new Audio("/tones/gs2.mp3"),
  A3: new Audio("/tones/a3.mp3"),
  "A#3": new Audio("/tones/as3.mp3"),
  B3: new Audio("/tones/b3.mp3"),
  C3: new Audio("/tones/c3.mp3"),
  "C#3": new Audio("/tones/cs3.mp3"),
  D3: new Audio("/tones/d3.mp3"),
  "D#3": new Audio("/tones/ds3.mp3"),
  E3: new Audio("/tones/e3.mp3"),
  F3: new Audio("/tones/f3.mp3"),
  "F#3": new Audio("/tones/fs3.mp3"),
  G3: new Audio("/tones/g3.mp3"),
  "G#3": new Audio("/tones/gs3.mp3"),
  A4: new Audio("/tones/a4.mp3"),
  "A#4": new Audio("/tones/as4.mp3"),
  B4: new Audio("/tones/b4.mp3"),
};

export const keyBindings = {
  Z: "C1",
  X: "C#1",
  C: "D1",
  V: "D#1",
  B: "E1",
  N: "F1",
  M: "F#1",
  ",": "G1",
  ".": "G#1",
  Q: "A2",
  W: "A#2",
  E: "B2",
  R: "C2",
  T: "C#2",
  Y: "D2",
  U: "D#2",
  I: "E2",
  O: "F2",
  P: "F#2",
  "[": "G2",
  "]": "G#2",
  A: "A3",
  S: "A#3",
  D: "B3",
  F: "C3",
  G: "C#3",
  H: "D3",
  J: "D#3",
  K: "E3",
  L: "F3",
  ";": "F#3",
  "'": "G3",
  "`": "G#3",
  1: "A4",
  2: "A#4",
  3: "B4",
};

export const noteBinings = {
  C1: "Z",
  "C#1": "X",
  D1: "C",
  "D#1": "V",
  E1: "B",
  F1: "N",
  "F#1": "M",
  G1: ",",
  "G#1": ".",
  A2: "Q",
  "A#2": "W",
  B2: "E",
  C2: "R",
  "C#2": "T",
  D2: "Y",
  "D#2": "U",
  E2: "I",
  F2: "O",
  "F#2": "P",
  G2: "[",
  "G#2": "]",
  A3: "A",
  "A#3": "S",
  B3: "D",
  C3: "F",
  "C#3": "G",
  D3: "H",
  "D#3": "J",
  E3: "K",
  F3: "L",
  "F#3": ";",
  G3: "'",
  "G#3": "`",
  A4: "1",
  "A#4": "2",
  B4: "3",
};
