export const notes = [
  "C1",
  "C#1",
  "D1",
  "D#1",
  "E1",
  "F1",
  "F#1",
  "G1",
  "G#1",
  "A2",
  "A#2",
  "B2",
  "C2",
  "C#2",
  "D2",
  "D#2",
  "E2",
  "F2",
  "F#2",
  "G2",
  "G#2",
  "A3",
  "A#3",
  "B3",
  "C3",
  "C#3",
  "D3",
  "D#3",
  "E3",
  "F3",
  "F#3",
  "G3",
  "G#3",
  "A4",
  "A#4",
  "B4",
];

export const audios = {
  C1: new Audio("/tones/c1.mp3"),
  "C#1": new Audio("/tones/cs1.mp3"),
  D1: new Audio("/tones/d1.mp3"),
  "D#1": new Audio("/tones/ds1.mp3"),
  E1: new Audio("/tones/e1.mp3"),
  F1: new Audio("/tones/f1.mp3"),
  "F#1": new Audio("/tones/fs1.mp3"),
  G1: new Audio("/tones/g1.mp3"),
  "G#1": new Audio("/tones/gs1.mp3"),
  A2: new Audio("/tones/a2.mp3"),
  "A#2": new Audio("/tones/as2.mp3"),
  B2: new Audio("/tones/b2.mp3"),
  C2: new Audio("/tones/c2.mp3"),
  "C#2": new Audio("/tones/cs2.mp3"),
  D2: new Audio("/tones/d2.mp3"),
  "D#2": new Audio("/tones/ds2.mp3"),
  E2: new Audio("/tones/e2.mp3"),
  F2: new Audio("/tones/f2.mp3"),
  "F#2": new Audio("/tones/fs2.mp3"),
  G2: new Audio("/tones/g2.mp3"),
  "G#2": new Audio("/tones/gs2.mp3"),
  A3: new Audio("/tones/a3.mp3"),
  "A#3": new Audio("/tones/as3.mp3"),
  B3: new Audio("/tones/b3.mp3"),
  C3: new Audio("/tones/c3.mp3"),
  "C#3": new Audio("/tones/cs3.mp3"),
  D3: new Audio("/tones/d3.mp3"),
  "D#3": new Audio("/tones/ds3.mp3"),
  E3: new Audio("/tones/e3.mp3"),
  F3: new Audio("/tones/f3.mp3"),
  "F#3": new Audio("/tones/fs3.mp3"),
  G3: new Audio("/tones/g3.mp3"),
  "G#3": new Audio("/tones/gs3.mp3"),
  A4: new Audio("/tones/a4.mp3"),
  "A#4": new Audio("/tones/as4.mp3"),
  B4: new Audio("/tones/b4.mp3"),
};

export const keyBindings = {
  Z: "C1",
  S: "C#1",
  X: "D1",
  D: "D#1",
  C: "E1",
  V: "F1",
  G: "F#1",
  B: "G1",
  H: "G#1",
  N: "A2",
  J: "A#2",
  M: "B2",
  Q: "C2",
  2: "C#2",
  W: "D2",
  3: "D#2",
  E: "E2",
  R: "F2",
  5: "F#2",
  T: "G2",
  6: "G#2",
  Y: "A3",
  7: "A#3",
  U: "B3",
  I: "C3",
  9: "C#3",
  O: "D3",
  0: "D#3",
  P: "E3",
  "[": "F3",
  "]": "F#3",
  "\\": "G3",
  ";": "G#3",
  "'": "A4",
  ",": "A#4",
  ".": "B4",
};

export const noteBinings = {
  C1: "Z",
  "C#1": "S",
  D1: "X",
  "D#1": "D",
  E1: "C",
  F1: "V",
  "F#1": "G",
  G1: "B",
  "G#1": "H",
  A2: "N",
  "A#2": "J",
  B2: "M",
  C2: "Q",
  "C#2": "2",
  D2: "W",
  "D#2": "3",
  E2: "E",
  F2: "R",
  "F#2": "5",
  G2: "T",
  "G#2": "6",
  A3: "Y",
  "A#3": "7",
  B3: "U",
  C3: "I",
  "C#3": "9",
  D3: "O",
  "D#3": "0",
  E3: "P",
  F3: "[",
  "F#3": "]",
  G3: "\\",
  "G#3": ";",
  A4: "'",
  "A#4": ",",
  B4: ".",
};
